### ISSUE TITLE
airma.sh permanently down as of late April 2019

### ISSUE THREAD

**Issue by Tinh1000000** [Matheus28/studio#19]
The airma.sh site has been permanently down as of late April 2019 [according to the subreddit for the game](https://www.reddit.com/r/airmash/comments/bgn8vu/airmash_server_down_seems_its_over_now/). There is a community-maintained instance running at https://airmash.online/, but during the last session I have checked in to that website, the game servers are temporarily(?) offline.

**Comment by Matheus28** [comment]
Thanks for letting me know. I have removed it from the listing.
