### ISSUE TITLE
Should be called "IO games"

### ISSUE THREAD

**Issue by BlazingFire007** [Matheus28/studio#5]
Everyone else calls them "IO games", I think you should change some of the wording from "browser MMO games" to "IO games" 

😉

**Comment by wwwg** [comment]
Agreed, i frequently see these games called "IO games"

**Comment by Matheus28** [comment]
"IO games" is not a descriptive term. It's worse than "MOBA".

**Comment by BlazingFire007** [comment]
https://news.ycombinator.com/item?id=14875822 
👀

**Comment by jjhesk** [comment]
check out iogame.space
